package jelte.mygame.graphical.audio;

public enum AudioCommand {
	MUSIC_PLAY_ONCE,
	MUSIC_PLAY_LOOP,
	MUSIC_STOP,
	MUSIC_STOP_ALL,
	SOUND_PLAY_ONCE,
	SOUND_PLAY_LOOP,
	SOUND_PLAY_LOOP_FOR,
	SOUND_STOP,
	MUSIC_PAUSE,
	MUSIC_RESUME,
	SOUND_PLAY_ONCE_WITH_COOLDOWN,
	SOUND_PLAY_LOOP_UNIQUE,
	STOP_ALL,
	PAUZE_ALL,
	RESUME_ALL
}
