package jelte.mygame.graphical.audio;

public enum AudioCommand {
	MUSIC_STOP,
	SOUND_PLAY_ONCE,
	SOUND_PLAY_LOOP,
	SOUND_PLAY_LOOP_FOR,
	SOUND_STOP,
	MUSIC_PAUSE,
	SOUND_PLAY_ONCE_WITH_COOLDOWN,
	SOUND_PLAY_LOOP_UNIQUE,
	STOP_ALL,
	PAUZE_ALL,
	RESUME_ALL,
	MUSIC_CHANGE_THEME,
	MUSIC_PLAY;
}
