name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        run: .\gradlew.bat test
  
      - name: Build executable
        run: .\gradlew.bat lwjgl3:dist

      - name: Perform code quality check
        run: .\gradlew.bat check

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: StickFighter3000-Windows
          path: lwjgl3/build/libs/
